@c -*- coding: utf-8-unix; mode: texinfo; mode: auto-fill; -*-
@c typographie française :    «   » … ’

@node Les images en Tcl
@chapter Les images en Tcl
@cindex Images
@findex image


@c @node Utiliser le format SVG
@section Utiliser le format SVG
@cindex SVG en Tcl

@c https://wiki.tcl-lang.org/page/SVG


@subsection Présentation  de SVG

SVG est un format vectoriel, qui permet donc de ne pas figer la taille
d'une image et de la redimensionner à l'infini.

Le format SVG est très proche du format utilisé par Canvas. Voir le
projet Coccinelle qui fait des traductions d'une image canvas en SVG.

Il est aussi proche de Java2D. La page Tcler's parle même d'une parenté
avec Postbresql et bien sûr Pdf.



@subsection Intégrer un image SVG dans un bouton.

Voici comment utiliser une image SVG dans un bouton. On commence par en
faire une photo avec ici une hauteur de 16 pixels. Ensuite, l'image peut
être intégrée.


@example
image create photo i1 -file ./test.svg -format @{svg -scaletoheight 16@}
pack [button .b1 -image i1]
@end example

On peut aussi reconfigurer la taille de l'image à 20 pixel en exécution.

@example
i1 configure -format @{svg -scaletoheight 20@}
@end example



